# Generated by Django 3.2.9 on 2022-01-23 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixtables',
            name='register_time',
            field=models.DateField(auto_now_add=True),
        ),
    ]
