# Generated by Django 3.2.9 on 2022-02-15 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_alter_fixtables_register_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='jointables',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
